/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoryRouteImport } from './routes/story'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as AdventureIndexRouteImport } from './routes/adventure.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as AdventureSlugRouteImport } from './routes/adventure.$slug'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdventuresRouteImport } from './routes/admin.adventures'
import { Route as PortfolioCategoryIndexRouteImport } from './routes/portfolio.$category.index'
import { Route as PortfolioCategoryProjectRouteImport } from './routes/portfolio.$category.$project'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdventureIndexRoute = AdventureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdventureRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdventureSlugRoute = AdventureSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdventureRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdventuresRoute = AdminAdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => AdminRoute,
} as any)
const PortfolioCategoryIndexRoute = PortfolioCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioCategoryRoute,
} as any)
const PortfolioCategoryProjectRoute =
  PortfolioCategoryProjectRouteImport.update({
    id: '/$project',
    path: '/$project',
    getParentRoute: () => PortfolioCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adventure': typeof AdventureRouteWithChildren
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/story': typeof StoryRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRouteWithChildren
  '/team/$slug': typeof TeamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/adventure/': typeof AdventureIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/team/': typeof TeamIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category/': typeof PortfolioCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/story': typeof StoryRoute
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/admin': typeof AdminIndexRoute
  '/adventure': typeof AdventureIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/team': typeof TeamIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category': typeof PortfolioCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adventure': typeof AdventureRouteWithChildren
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/story': typeof StoryRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/adventures': typeof AdminAdventuresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRouteWithChildren
  '/team/$slug': typeof TeamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/adventure/': typeof AdventureIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/team/': typeof TeamIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category/': typeof PortfolioCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adventure'
    | '/contact'
    | '/csr'
    | '/portfolio'
    | '/story'
    | '/team'
    | '/admin/adventures'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/staff'
    | '/adventure/$slug'
    | '/portfolio/$category'
    | '/team/$slug'
    | '/admin/'
    | '/adventure/'
    | '/portfolio/'
    | '/team/'
    | '/portfolio/$category/$project'
    | '/portfolio/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/csr'
    | '/story'
    | '/admin/adventures'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/staff'
    | '/adventure/$slug'
    | '/team/$slug'
    | '/admin'
    | '/adventure'
    | '/portfolio'
    | '/team'
    | '/portfolio/$category/$project'
    | '/portfolio/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adventure'
    | '/contact'
    | '/csr'
    | '/portfolio'
    | '/story'
    | '/team'
    | '/admin/adventures'
    | '/admin/login'
    | '/admin/projects'
    | '/admin/staff'
    | '/adventure/$slug'
    | '/portfolio/$category'
    | '/team/$slug'
    | '/admin/'
    | '/adventure/'
    | '/portfolio/'
    | '/team/'
    | '/portfolio/$category/$project'
    | '/portfolio/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdventureRoute: typeof AdventureRouteWithChildren
  ContactRoute: typeof ContactRoute
  CsrRoute: typeof CsrRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  StoryRoute: typeof StoryRoute
  TeamRoute: typeof TeamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/adventure/': {
      id: '/adventure/'
      path: '/'
      fullPath: '/adventure/'
      preLoaderRoute: typeof AdventureIndexRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/adventure/$slug': {
      id: '/adventure/$slug'
      path: '/$slug'
      fullPath: '/adventure/$slug'
      preLoaderRoute: typeof AdventureSlugRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adventures': {
      id: '/admin/adventures'
      path: '/adventures'
      fullPath: '/admin/adventures'
      preLoaderRoute: typeof AdminAdventuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portfolio/$category/': {
      id: '/portfolio/$category/'
      path: '/'
      fullPath: '/portfolio/$category/'
      preLoaderRoute: typeof PortfolioCategoryIndexRouteImport
      parentRoute: typeof PortfolioCategoryRoute
    }
    '/portfolio/$category/$project': {
      id: '/portfolio/$category/$project'
      path: '/$project'
      fullPath: '/portfolio/$category/$project'
      preLoaderRoute: typeof PortfolioCategoryProjectRouteImport
      parentRoute: typeof PortfolioCategoryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdventuresRoute: typeof AdminAdventuresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdventuresRoute: AdminAdventuresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdventureRouteChildren {
  AdventureSlugRoute: typeof AdventureSlugRoute
  AdventureIndexRoute: typeof AdventureIndexRoute
}

const AdventureRouteChildren: AdventureRouteChildren = {
  AdventureSlugRoute: AdventureSlugRoute,
  AdventureIndexRoute: AdventureIndexRoute,
}

const AdventureRouteWithChildren = AdventureRoute._addFileChildren(
  AdventureRouteChildren,
)

interface PortfolioCategoryRouteChildren {
  PortfolioCategoryProjectRoute: typeof PortfolioCategoryProjectRoute
  PortfolioCategoryIndexRoute: typeof PortfolioCategoryIndexRoute
}

const PortfolioCategoryRouteChildren: PortfolioCategoryRouteChildren = {
  PortfolioCategoryProjectRoute: PortfolioCategoryProjectRoute,
  PortfolioCategoryIndexRoute: PortfolioCategoryIndexRoute,
}

const PortfolioCategoryRouteWithChildren =
  PortfolioCategoryRoute._addFileChildren(PortfolioCategoryRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRouteWithChildren
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRouteWithChildren,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdventureRoute: AdventureRouteWithChildren,
  ContactRoute: ContactRoute,
  CsrRoute: CsrRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  StoryRoute: StoryRoute,
  TeamRoute: TeamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
