/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoryRouteImport } from './routes/story'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as AdventureIndexRouteImport } from './routes/adventure.index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as AdventureSlugRouteImport } from './routes/adventure.$slug'
import { Route as PortfolioCategoryIndexRouteImport } from './routes/portfolio.$category.index'
import { Route as PortfolioCategoryProjectRouteImport } from './routes/portfolio.$category.$project'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdventureIndexRoute = AdventureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdventureRoute,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdventureSlugRoute = AdventureSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdventureRoute,
} as any)
const PortfolioCategoryIndexRoute = PortfolioCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioCategoryRoute,
} as any)
const PortfolioCategoryProjectRoute =
  PortfolioCategoryProjectRouteImport.update({
    id: '/$project',
    path: '/$project',
    getParentRoute: () => PortfolioCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRouteWithChildren
  '/adventure/': typeof AdventureIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category/': typeof PortfolioCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/adventure': typeof AdventureIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category': typeof PortfolioCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/adventure/$slug': typeof AdventureSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRouteWithChildren
  '/adventure/': typeof AdventureIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/$category/$project': typeof PortfolioCategoryProjectRoute
  '/portfolio/$category/': typeof PortfolioCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/contact'
    | '/csr'
    | '/portfolio'
    | '/story'
    | '/team'
    | '/adventure/$slug'
    | '/portfolio/$category'
    | '/adventure/'
    | '/portfolio/'
    | '/portfolio/$category/$project'
    | '/portfolio/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/csr'
    | '/story'
    | '/team'
    | '/adventure/$slug'
    | '/adventure'
    | '/portfolio'
    | '/portfolio/$category/$project'
    | '/portfolio/$category'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/contact'
    | '/csr'
    | '/portfolio'
    | '/story'
    | '/team'
    | '/adventure/$slug'
    | '/portfolio/$category'
    | '/adventure/'
    | '/portfolio/'
    | '/portfolio/$category/$project'
    | '/portfolio/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRouteWithChildren
  ContactRoute: typeof ContactRoute
  CsrRoute: typeof CsrRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  StoryRoute: typeof StoryRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/adventure/': {
      id: '/adventure/'
      path: '/'
      fullPath: '/adventure/'
      preLoaderRoute: typeof AdventureIndexRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/adventure/$slug': {
      id: '/adventure/$slug'
      path: '/$slug'
      fullPath: '/adventure/$slug'
      preLoaderRoute: typeof AdventureSlugRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/portfolio/$category/': {
      id: '/portfolio/$category/'
      path: '/'
      fullPath: '/portfolio/$category/'
      preLoaderRoute: typeof PortfolioCategoryIndexRouteImport
      parentRoute: typeof PortfolioCategoryRoute
    }
    '/portfolio/$category/$project': {
      id: '/portfolio/$category/$project'
      path: '/$project'
      fullPath: '/portfolio/$category/$project'
      preLoaderRoute: typeof PortfolioCategoryProjectRouteImport
      parentRoute: typeof PortfolioCategoryRoute
    }
  }
}

interface AdventureRouteChildren {
  AdventureSlugRoute: typeof AdventureSlugRoute
  AdventureIndexRoute: typeof AdventureIndexRoute
}

const AdventureRouteChildren: AdventureRouteChildren = {
  AdventureSlugRoute: AdventureSlugRoute,
  AdventureIndexRoute: AdventureIndexRoute,
}

const AdventureRouteWithChildren = AdventureRoute._addFileChildren(
  AdventureRouteChildren,
)

interface PortfolioCategoryRouteChildren {
  PortfolioCategoryProjectRoute: typeof PortfolioCategoryProjectRoute
  PortfolioCategoryIndexRoute: typeof PortfolioCategoryIndexRoute
}

const PortfolioCategoryRouteChildren: PortfolioCategoryRouteChildren = {
  PortfolioCategoryProjectRoute: PortfolioCategoryProjectRoute,
  PortfolioCategoryIndexRoute: PortfolioCategoryIndexRoute,
}

const PortfolioCategoryRouteWithChildren =
  PortfolioCategoryRoute._addFileChildren(PortfolioCategoryRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRouteWithChildren
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRouteWithChildren,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRouteWithChildren,
  ContactRoute: ContactRoute,
  CsrRoute: CsrRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  StoryRoute: StoryRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
